---
# file: playbook.yml
#   Shortcut to run install tasks on the localhost without setting up an inventory.
- hosts: localhost
  connection: local
  vars:
    galaxy_config_style: yaml
    galaxy_layout: legacy-improved
    galaxy_server_dir: /galaxy/server
    galaxy_commit_id: release_21.01
    galaxy_repo: https://github.com/galaxyproject/galaxy.git
    galaxy_clone_depth: 1
    galaxy_virtualenv_command: /usr/bin/python3 -m virtualenv
    galaxy_virtualenv_python: python3
    pip_extra_args: "--no-cache-dir --compile"
    galaxy_manage_database: false
    galaxy_client_make_target: client-production
    galaxy_config_files:
      - src: files/job_conf.xml
        dest: "{{ galaxy_server_dir }}/config/job_conf.xml"
      - src: files/welcome.html
        dest: "{{ galaxy_server_dir }}/static/welcome.html"
    galaxy_config:
      uwsgi:
        virtualenv: "{{ galaxy_server_dir }}/.venv"
        pythonpath: "{{ galaxy_server_dir }}/lib"
        mount: /=galaxy.webapps.galaxy.buildapp:uwsgi_app()
        http: 0.0.0.0:8080
        manage-script-name: true
        static-map:
          - /static/style={{ galaxy_server_dir }}/static/style/blue
          - /static={{ galaxy_server_dir }}/static
          - /favicon.ico=/galaxy/server/static/favicon.ico
        static-safe: /galaxy/server/client/galaxy/images
        thunder-lock: true
        buffer-size: 16384
        offload-threads: 2
        processes: 1
        threads: 4
        die-on-term: true
        master: true
        hook-master-start: unix_signal:2 gracefully_kill_them_all
        enable-threads: true
        py-call-osafterfork: true
      galaxy:
        conda_auto_init: false
  roles:
    - galaxy
